apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
      - env:
        - name: SW_OAP_ADDRESS
          value: oap:12800
        image: apache/skywalking-ui:6.6.0
        name: ui
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
